clinicaltrials/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', views.about_clinical_research, name='home'),
    url(r'^study/', include('study.urls', namespace='study')),
]

urlpatterns += i18n_patterns(
    # url(r'^admin_tools/', include('admin_tools.urls')),
    # url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
)

urlpatterns += staticfiles_urlpatterns()

study/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.study, name='study'),
    # url(r'^details/$', views.study_details, name='study_details'),
    url(r'^study_identifiers/$', views.study_identifiers, name='study_identifiers'),
    url(r'^basic_information/$', views.basic_information, name='basic_information'),
    url(r'^eligibility/$', views.eligibility, name='eligibility'),
    url(r'^place/$', views.place, name='place'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    # url(r'^(?P<category_slug>[-\w]+)/$', views.shop, name='product_index_by_category'),
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

templates/includes/footer.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
  </body>
</html>

templates/includes/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../favicon.ico">-->
{#    <style>#}
{#      body {#}
{#          background: #3c68ff url('../../static/img/3.jpg') no-repeat;#}
{#          background-size: 100%;#}
{#      }#}
{#    </style>#}
    <title>Розвиток клінічних досліджень в Україні</title>
    <!-- Bootstrap core CSS -->
    <link href="../../static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="../../static/css/navbar-static-top.css" rel="stylesheet">
  </head>
  <body>

            <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <form class="navbar-form navbar-left">
                <input type="text" placeholder="Email" class="form-control">
                <input type="password" placeholder="Пароль" class="form-control">
                <button type="submit" class="btn btn-success">Вхід</button>
              </form>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Пошук...">
                <button type="button" class="btn btn-info" aria-label="Left Align">
                <span class="glyphicon glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </form>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/includes/main_navbar.html
    <div class="container">
{#    <nav class="navbar navbar-default navbar-fixed-top">#}
{#        <div class="container-fluid">#}
{#          <div class="navbar-header">#}
{#            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">#}
{#              <span class="sr-only">Toggle navigation</span>#}
{#              <span class="icon-bar"></span>#}
{#              <span class="icon-bar"></span>#}
{#              <span class="icon-bar"></span>#}
{#            </button>#}
{#            <a class="navbar-brand" href="{% url 'index' %}" title="Always to the greetings page!">Clinicaltrials</a>#}
{#          </div>#}
{#          <div>#}
{#              {% if user.is_authenticated %}#}
{#                <li><a href="{% url 'users:logout' %}">Logout</a></li>#}
{#                <li role="presentation" {% if '/profile' in request.path %}class="active"{% endif %}><a href="{% url 'users:profile' slug=user.username %}">{{ user.username }}</a></li>#}
{#              {% else %}#}
{#                <li><a href="{% url 'users:userprofiles_registration' %}">Register</a></li>#}
{#                <li ><a href="{% url 'users:login' %}">Login</a></li>#}
{#              {% endif %}#}
{#          </div>#}
{#          <div id="navbar" class="navbar-collapse collapse">#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#              <li role="presentation" {% if '/study' in request.path %}class="active"{% endif %}><a href="{% url 'study:study' %}">Studies</a></li>#}
{#              <li role="presentation" {% if '/about' in request.path %}class="active"{% endif %}><a href="#">Additional Info</a></li>#}
{#            </ul>#}
{#            <form class="navbar-form navbar-right">#}
{#              {% csrf_token %}#}
{#              <input type="text" class="form-control" placeholder="Search...">#}
{#            </form>#}
{#          </div>#}
{#        </div>#}
{#    </nav>#}
{#</div>#}
      <div class="jumbotron" style="background-color: #ffc35c;">
        <div class="row">
          <div class="col-md-6">
            <h1 style="text-align: center;">Clinical Trials</h1>
            <h2 style="text-align: center;">in Ukraine</h2>
          </div>
          <div class="col-md-6">
            <a href="{% url 'home' %}"><button type="button" class="btn btn-primary btn-lg btn-block">Що таке клінічні дослідження</button></a>
            <br>
            <a href="{% url 'study:study' %}"><button type="button" class="btn btn-primary btn-lg btn-block">Знайти дослідження</button></a>
          </div>
        </div>
      </div>

templates/includes/navtabs.html
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" {%  if '/study_identifiers' in request.path %}class="active"{% endif %}><a href="{% url 'study:study_identifiers' %}">Ідентифікатор клінічного дослідження</a></li>
  <li role="presentation" {%  if '/basic_information' in request.path %}class="active"{% endif %}><a href="{% url 'study:basic_information' %}">Базова інформація</a></li>
  <li role="presentation" {%  if '/eligibility' in request.path %}class="active"{% endif %}><a href="{% url 'study:eligibility' %}">Критерії відбору</a></li>
  <li role="presentation" {%  if '/place' in request.path %}class="active"{% endif %}><a href="{% url 'study:place' %}">Місця проведення</a></li>
  <li role="presentation" {%  if '/contacts' in request.path %}class="active"{% endif %}><a href="{% url 'study:contacts' %}">Контакти</a></li>
</ul>